<Project Sdk="Microsoft.NET.Sdk">

<Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- <TargetFramework>net8.0</TargetFramework> -->
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>d1cc9f8d-0675-4d71-b052-adc4e37bdf0d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.2.2" />
    <!-- SQL Server hosting support for Aspire -->
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="8.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\backend\ObituaryApp\ObituaryApp.csproj" />
    <ProjectReference Include="..\frontend\frontend.csproj" />
  </ItemGroup>

</Project>

