name: Build and Deploy to Azure Web App (Container)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # (Removed secret validation step — using secrets directly in the deploy step below.)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore backend/ObituaryApp

    - name: Build
      run: dotnet build backend/ObituaryApp -c Release --no-restore

    - name: Publish
      run: dotnet publish backend/ObituaryApp -c Release -o ./publish

    - name: Zip publish output
      run: |
        apt-get update && apt-get install -y zip || true
        zip -r publish.zip ./publish

    - name: Deploy to Azure Web App using Publish Profile
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish.zip

    - name: Completed
      run: echo "Deployment step finished. Configure secrets AZURE_WEBAPP_NAME and AZURE_WEBAPP_PUBLISH_PROFILE in repository settings."
