# DISABLED - Using Azure DevOps pipeline instead to meet assignment requirements
# This workflow is disabled to avoid conflicts with the trigger-azure-pipeline.yml workflow
# which meets the assignment requirement: "Set up GitHub Actions to trigger Azure DevOps pipeline on push to main branch"

name: DISABLED - Direct Azure Deploy

# Workflow is disabled - no triggers defined
on: []

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled
        run: echo "This workflow is disabled. Using Azure DevOps pipeline instead to meet assignment requirements."
